server:
  port: 8000

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/h976353715/cloud-cms.git
          username:
          password:
          #basedir: config-repo
          search-paths: cloud-config-repo
      overrideNone: true
      label: master
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/


