server:
  port: 9000
spring:
  application:
    name: cloud-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hq_account?characterEncoding=UTF-8
    username: root
    password: root
   # type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.hq.clouduser.pojo
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  level:
    com.hq.clouduser.dao: debug

