server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
logging:
  level:
    com.hq.*: debug

spring:
  application:
    name: gateway-server
  security:
    user:
      password: none


zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cloud-user

security:
  oauth2:
    client:
      client-id: hq
      client-secret: hq
      access-token-uri: http://localhost:8000/auth/token
      userAuthorizationUri: http://localhost:8000/auth/authorize
    resource:
      userInfoUri: http://localhost:8000/auth/user
      jwt:
        key-uri: http://localhost:8000/auth/token_key
        key-value: -----BEGIN PUBLIC KEY-----
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsep44Kxa/eOqImFp9N+7
                   rcfphlSyjtKSruukJTWVdNbS0zs5mGJMubLLGMGHemIixw6J+8PGPbqbS2Sd8Tx/
                   vu6Mjfxq4GwHdfDzIqkL6LT1XDPTQmMpMTfASIS3NGaU1yb1D/D43ZNBjKrGAVUa
                   otlmO5NFsejvSbFd+FDdsVbXVLePe7tHYOdpU8uko7HwmxIG3c8W43TZrGd8nCnT
                   rr18/jo+l0POMrROpgnK7OnHr7CSG7Jz+uUJ/wwf+gwyj1Y+AduXcesBTTzg89DL
                   hYdFNpwgII4vXrDIkIf8orO0gBsB4LwZh37YSFadTmcMOkZ9x6XviZez/Grnprkq
                   FQIDAQAB
                   -----END PUBLIC KEY-----







