server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
logging:
  level:
    com.hq.*: debug

spring:
  application:
    name: biz-server


zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cloud-user


security:
  oauth2:
    client:
      clientId: hq
      clientSecret: hq
      userAuthorizationUri: http://localhost:8000/oauth/authorize
      grant-type: password
      scope: xx
      access-token-uri: http://localhost:8000/oauth/token
    resource:
      userInfoUri: http://localhost:8000/user
    authorization:
      check-token-access: http://localhost:8000/oauth/check_token


feign:
  hystrix:
    enabled: true


